# TensorFlow
    TensorFlow is an open source library for numerical computation using data flow graphs
    
# Tensors
A tensor can have any number of dimensions:
* <b>scalar</b>: a zero-dimensional collection(tensor rank 0)
* <b>vector</b>: a one-dimensional collection(tensor rank 1)
* <b>matrix</b>: a two-dimensional collection(tensor rank 2)
* <b>tensor</b>: multidimensional collection(tensor rank > 2)


## Different Tensors 
    * Variables
    * Constants
    * Operations
    * Tensors generated from library functions

### Install TensorFlow

In [ ]:
# CPU
!pip install --upgrade pip
!pip install --upgrade tensorflow==2.0.0-beta1

### Import TensorFlow

In [5]:
import tensorflow as tf
import numpy as np

### Check Version

In [2]:
tf.__version__

'2.0.0'

In [2]:
print('TensorFlow version: {}'.format(tf.__version__))
print('Eager execution is: {}'.format(tf.executing_eagerly()))
print('Keras version: {}'.format(tf.keras.__version__))

TensorFlow version: 2.0.0
Eager execution is: True
Keras version: 2.2.4-tf


### GPU

In [3]:
tf.test.is_gpu_available()

False

In [4]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

Running on CPU


### Declaring Variables

In [17]:
w = tf.Variable(np.zeros(shape=(2,1)))

In [16]:
w.shape

TensorShape([2, 1])

In [12]:
t0 = 24 # python variable 
t1 = tf.Variable(42) # rank 0 tensor 
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

### Datatype can be explicitly specified


In [18]:
f64 = tf.Variable(89, dtype = tf.float64) 
f64.dtype

tf.float64

### َAssign Value

In [22]:
f1 = tf.Variable([[89.], [78.]]) 
f1.shape

TensorShape([2, 1])

In [23]:
f1.assign([[89.], [-1]])
f1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[89.],
       [-1.]], dtype=float32)>

In [20]:
# assign value
f1 = tf.Variable(89.) 
print(f1)
f1.assi
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [21]:
f1.numpy()

98.0

## Constants

In [25]:
cons = tf.constant(42) 
print(cons) 
cons.numpy()

tf.Tensor(42, shape=(), dtype=int32)


42

### Shaping a tensor

In [26]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ])
print(t2.shape)

(2, 2, 3)


### Reshaping Tesors

In [27]:
t2 = tf.Variable(np.ones(shape=(1,12)))
t2

<tf.Variable 'Variable:0' shape=(1, 12) dtype=float64, numpy=array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])>

In [28]:
r1 = tf.reshape(t2, [2, 6]) # 2 rows 6 cols
r1

<tf.Tensor: id=110, shape=(2, 6), dtype=float64, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])>

In [29]:
r2 = tf.reshape(t2, [-1, 1])
r2

<tf.Tensor: id=113, shape=(12, 1), dtype=float64, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])>

### Specifying an element of a tensor

In [32]:
t3 = t2[0, 1]
t3

<tf.Tensor: id=126, shape=(), dtype=float64, numpy=1.0>

In [33]:
len(t3.shape)

0

### Casitng a tensor to a Numpy/Python variable

In [37]:
t2.numpy().shape

(1, 12)

In [38]:
print('t2: ', t2.numpy(),'\n')
print('t2-slice: ', t2[1, 0].numpy())

t2:  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 



InvalidArgumentError: slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

### Finding the size of an element

In [43]:
s = tf.size(input=t2).numpy()
s

12

### finding the datatype of a tensor

In [41]:
t3.dtype

tf.float64

## Operations

### Specifying element-wise primitive tensor operations

In [44]:
t2.numpy()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
t2 * t2

<tf.Tensor: id=151, shape=(1, 12), dtype=float64, numpy=array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])>

### Broadcasting

In [46]:
t4 = t2 * 4
t4

<tf.Tensor: id=154, shape=(1, 12), dtype=float64, numpy=array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])>

### Transposing TensorFlow and matrix multiplication

In [49]:
u = tf.constant([[3, 4, 3]])
v = tf.constant([[1, 2, 1]])
tf.matmul(u, tf.transpose(v))
# There is a complete list of these operations at https://www.tensorflow.org/api_guides/python/math_ops

<tf.Tensor: id=161, shape=(1, 1), dtype=int32, numpy=array([[14]])>

### Casting

In [51]:
t4.dtype

tf.float64

In [52]:
i = tf.cast(t4, dtype=tf.int32) 
i

<tf.Tensor: id=162, shape=(1, 12), dtype=int32, numpy=array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])>

In [53]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: id=164, shape=(), dtype=int32, numpy=4>

## Providing useful TensorFlow operations

## Squared difference

In [54]:
x = [1, 3, 5, 7, 11]
y = 5
s = tf.math.squared_difference(x, y)
s

<tf.Tensor: id=167, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>

### Mean

In [57]:
numbers = tf.constant([[4, 5], [7, 3]])
print(numbers.numpy())
tf.reduce_mean(input_tensor=numbers)

[[4 5]
 [7 3]]


<tf.Tensor: id=176, shape=(), dtype=int32, numpy=4>

### Finding the mean across columns

In [62]:
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=184, shape=(2,), dtype=int32, numpy=array([4, 5])>

### Keepdims

In [66]:
tf.transpose(tf.reduce_mean(input_tensor=numbers, keepdims=True, axis=0))

<tf.Tensor: id=194, shape=(2, 1), dtype=int32, numpy=
array([[5],
       [4]])>

### Finding the mean across rows

In [67]:
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=196, shape=(2,), dtype=int32, numpy=array([4, 5])>

### Random distributions

In [68]:
ran =  tf.random.normal(shape=(3, 2), mean=10, stddev=2, dtype=tf.float32)
print(ran)

tf.Tensor(
[[10.454605  8.14479 ]
 [11.199692  7.625861]
 [13.614147 12.679537]], shape=(3, 2), dtype=float32)


In [39]:
# uniform distribution
tf.random.uniform(shape=(2, 4) , minval=0, maxval=10)

<tf.Tensor: id=314, shape=(2, 4), dtype=float32, numpy=
array([[3.4551501, 3.2003427, 1.3557363, 8.878182 ],
       [9.725767 , 8.116491 , 3.7258077, 3.284669 ]], dtype=float32)>

In [40]:
# random seed
tf.random.set_seed(11) 
ran_1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32) 
ran_2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32) 
print(ran_1) #Call 1 
print(ran_2)

tf.random.set_seed(11) #same seed 
ran_1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32) 
ran_2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32) 
print(ran_1) #Call 2 
print(ran_2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


### Argmax - Argmin

In [36]:
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
i = tf.argmax(input=t5)

print('index of max; ', i) 
print('Max element: ',t5[i].numpy())

i = tf.argmin(input=t5)
print('index of min: ', i) 
print('Min element: ',t5[i].numpy())

index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  tf.Tensor(7, shape=(), dtype=int64)
Min element:  -11


### Argmax - Argmin across columns

In [37]:
t6 = tf.reshape(t5, [3,3])
print(t6) 
i = tf.argmax(input=t6, axis=0).numpy() # max arg down rows 
print('indices of max down rows; ', i) 
i = tf.argmin(input=t6, axis=0).numpy() # min arg down rows 
print('indices of min down rows ; ',i)
print(t6)

tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)


### Saving and restoring tensor values using a checkpoint

In [48]:
variable = tf.Variable([[1, 3, 5, 7], [11, 13, 17, 19]])
print(variable)
chechpoint = tf.train.Checkpoint(var=variable)
save_path = chechpoint.save('./vars')
variable.assign([[0,0,0,0], [0,0,0,0]])
print(variable)
chechpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>


### Declaring ragged tensors

In [28]:
# A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.

ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged) 
print(ragged[0,:]) 
print(ragged[1,:])
print(ragged[2,:]) 
print(ragged[3,:]) 
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [29]:
ragged = tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6, 7], row_splits=[0, 4, 4, 7, 8, 10])
ragged

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>

*:)*