In [1]:
import numpy as np

### How to create an 1d_array

In [2]:
a = np.array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [4]:
a.dtype

dtype('int32')

#### Set dtype explicity

In [7]:
a = np.array([[1,2,3.5,4,5]], dtype=np.float64)
a

array([[1. , 2. , 3.5, 4. , 5. ]])

In [9]:
a.ndim, a.shape, a.size , a.dtype, a.sum()

(2, (1, 5), 5, dtype('float64'), 15.5)

In [10]:
a = a.astype(np.int32)
a

array([[1, 2, 3, 4, 5]])

In [11]:
a.dtype

dtype('int32')

### How to create an nd_array

In [12]:
lst = [[1,2,3,4,5],
       [6,7,8,9,10]]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [13]:
b = np.array(lst, dtype=np.float64)

In [14]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [15]:
b.dtype

dtype('float64')

In [16]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

### functions of numpy

In [17]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((4,4))

array([[4.67296746e-307, 1.69121096e-306, 1.37962117e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        3.60081101e+228]])

In [ ]:
np.linspace()

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### stacking

In [30]:
a = np.zeros((2, 3))
b = np.ones((2, 3))

In [31]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.vstack([a, b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.hstack([a,b])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [37]:
np.concatenate((a, b), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

### Transpose

In [40]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a.transpose()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a.shape

### dummy array

In [50]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [51]:
a.shape

(4,)

In [52]:
b = a.T
b.shape

(4,)

In [53]:
np.all(b == a)

True

In [54]:
a = np.array([[1, 2, 3, 4]])
a.shape

(1, 4)

In [55]:
b = a.T
b.shape

(4, 1)

In [56]:
np.all(b == a)

False

### save & load

In [57]:
np.save('example.npy', a)

In [59]:
a1 = np.load('example.npy')

In [60]:
a1

array([[1, 2, 3, 4]])

In [61]:
np.all(a1 == a)

True

### broadcasting

In [62]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [64]:
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [65]:
ones = np.ones((6, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
twos = np.ones((6,1)) * 2
twos

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.]])

In [67]:
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
twos = np.ones((6,2)) * 2
ones + twos

### Check the speed of arrays!!

In [68]:
x = np.linspace(0,100,10000000)

In [69]:
x.size

10000000

In [71]:
import math
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

In [72]:
%timeit get_lst(x)

3.4 s ± 118 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [73]:
%timeit np.sin(x)

52 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [74]:
3.4 / (52 * 0.001)

65.38461538461537

*:)*