In [1]:
import numpy as np

### Vector

In [2]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
v[0], v[1], v[-1]

(0.0, 2.5, 10.0)

In [4]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

### Matirx

In [5]:
vv = np.random.random((5,4))
vv

array([[0.80651507, 0.14968182, 0.79758186, 0.75413049],
       [0.48809246, 0.04009566, 0.08279988, 0.12474019],
       [0.17772896, 0.96302176, 0.68115889, 0.66580917],
       [0.44255396, 0.06279219, 0.61748218, 0.85082414],
       [0.23219992, 0.79728447, 0.99088813, 0.84205393]])

In [6]:
vv[0,0]

0.8065150734207199

In [7]:
vv[4,3]

0.8420539339812875

In [8]:
ll = [[1,2,3],[4,5,6],[7,8,9]]
ll[1][2]

6

In [9]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [10]:
vv[2:5,1]

array([0.96302176, 0.06279219, 0.79728447])

In [ ]:
vv[2:5,1:2]

In [ ]:
vv[2:-1,:]

#### Numpy arrays are mutable

In [11]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
v2 = v
v2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
v2[2] = 0
v2

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [14]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [15]:
v3 = v.copy()
v3

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [16]:
v3[0] = 1
v3

array([ 1. ,  2.5,  0. ,  7.5, 10. ])

In [17]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

### boolean mask

In [25]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
bool_index = v > 0
bool_index

array([False,  True,  True,  True,  True])

In [28]:
v[bool_index]

array([ 2.5,  5. ,  7.5, 10. ])

In [29]:
vv = np.random.random((5,4))
vv

array([[0.96731301, 0.51100026, 0.62287302, 0.24915675],
       [0.81744088, 0.29198136, 0.65844772, 0.73089035],
       [0.62706505, 0.50599655, 0.61654389, 0.54210849],
       [0.3715571 , 0.13030663, 0.54442312, 0.3662166 ],
       [0.93800557, 0.18363552, 0.90095334, 0.87121244]])

In [30]:
vv[vv > 0.5] = 0.0
vv

array([[0.        , 0.        , 0.        , 0.24915675],
       [0.        , 0.29198136, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.3715571 , 0.13030663, 0.        , 0.3662166 ],
       [0.        , 0.18363552, 0.        , 0.        ]])

### Multi-index assignment

In [31]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
v[[0,3,1]] = [4,5,-2.5]
v

array([ 4. , -2.5,  5. ,  5. , 10. ])

*:)*